### ISSUE TITLE
help webpack error

### ISSUE THREAD

**Issue by JohnKeng** [15Dkatz/es6-tutorial#1]
I follow video step by step create the build.js 
But I fail,WHY?
[es6.zip](https://github.com/15Dkatz/es6-tutorial/files/748056/es6.zip)
![2017-02-02 pm10 54 36](https://cloud.githubusercontent.com/assets/1924712/22554357/b6be47b8-e99a-11e6-9029-6ba1eb5e36ff.png)

**Comment by 15Dkatz** [comment]
Hi, I saw your question on Udemy. Try running `npm install` and then `npm install webpack` specifically.

**Comment by 15Dkatz** [comment]
FWIW, fixed the problem by running 'npm install webpack -g'
